# Generated by Django 3.1.1 on 2022-07-20 16:59

import accounts.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('43402145-da25-4420-bcc1-dee9f9f19b9c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
